remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
- jekyll-remote-theme
- jekyll-include-cache

title: The title of your site
description: A short description of your site's purpose

show_downloads: false

google_analytics: 
