remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
- jekyll-remote-theme
- jekyll-include-cache

minimal_mistakes_skin: "dark" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

title: "The title of your site"
title_separator: "|"

subtitle: "This is the subtitle"

description: "A short description of your site's purpose"

url: "https://grubermarkus.github.io" # or url: "https://example.com" if you have a custom domain name.
baseurl: "/GruberMarkus"
repository: "GruberMarkus/GruberMarkus"

logo: "/assets/images/88x88.png"

lunr:
  search_within_pages: true
  search_full_content: true

# Open Graph
# og_image: /assets/images/site-logo.png
